# Generated by Django 4.0.2 on 2022-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offlinetraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='onlinetraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
            ],
        ),
    ]
