# Generated by Django 4.0.2 on 2022-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessproapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymenttrainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(max_length=240, null=True)),
                ('name', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifsc', models.CharField(max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paymenttrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(max_length=240, null=True)),
                ('name', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifsc', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
