# Generated by Django 4.0.2 on 2022-04-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessproapp', '0003_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('username', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(max_length=240, null=True)),
                ('status', models.CharField(default='trainee', max_length=240, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymenttrainee',
            name='sname',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
