# Generated by Django 4.0.2 on 2022-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessproapp', '0004_user_registration_paymenttrainee_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinetraining',
            name='status',
            field=models.CharField(default='New', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='onlinetraining',
            name='status',
            field=models.CharField(default='New', max_length=240, null=True),
        ),
    ]
