# Generated by Django 4.0.2 on 2022-05-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessproapp', '0005_offlinetraining_status_onlinetraining_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinetraining',
            name='plan',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='onlinetraining',
            name='plan',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
