# Generated by Django 4.0.2 on 2022-10-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessproapp', '0006_offlinetraining_plan_onlinetraining_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offlinetraining',
        ),
        migrations.DeleteModel(
            name='onlinetraining',
        ),
        migrations.DeleteModel(
            name='paymenttrainee',
        ),
        migrations.DeleteModel(
            name='paymenttrainer',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='day',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='fromtime',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='totime',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='workoutcate',
        ),
        migrations.AddField(
            model_name='batch',
            name='vdes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='vmodel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='vnum',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='vtype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
